#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
1

temp = None
x = input("Введите значение X:")
y = input("Введите значение Y:")

temp = x
x = y
y = temp
print(f"Меняем значения переменных, получаем: X - {x} и Y - {y}")

2

time = int(input("Ввести время в секундах: "))
hours = time // 3600
minutes = (time // 60) - (hours * 60)
seconds = time % 60
print(f"{hours:02}:{minutes:02}:{seconds:02}")

3

n = input("Enter an integer:")
print(f{n} + {n + n} + {n + n + n} = {int(n) + int(n + n) + int(n + n + n)}")

4

num_init = int(input("enter a positive integer"))
greatest_dig = 0 
num = num_init

while num > 0:
    digit = num % 10
    if digit > greatest_dig:
        greatest_dig = digit
        if greatest_dig == 9:
            break
    num = num // 10
print(f"Highest number somewhere {num_init} equals {geatest_dig})

5

revenue = float(input("Введите значение выручки") - ")
costs = float(input("Введите значение издержек") - ")
result = revenue - costs 

if result > 0:
    print(f"прибыль {result}!")
    print(f"рентабельность {result/revenue: .3f}")
    personal_n = int(input("...")) 
    print(f"..."{result / personal_n:.3f} тугриков.")
elif result < 0:
    print(f"... {-result}...")
else:
    print(f"...")
    

6

while True:
    days = 1
    start_km = int(input("Starting result:"))
    last_km = int(input ("Ending result:"))
    if start_km < 0 or last_km < 0:
        print("Results have to be more than 0")
    else:
        while start_km < last_km:
            start_km += start_km * 0.1
            days += 1
            
        print(f"...{days}...")
        break
    
